# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: luslab-clip-0.1
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  ## basic packages
  - pigz=2.3.4

  ## bioconda packages, see above
  - fastqc=0.11.8
  - cutadapt=2.6
  - bowtie=1.2.3
  - star=2.7.3a
  - bedtools=2.28.0
  - umi_tools=1.0.1
  - ucsc-bedsort=377
  - sambamba=0.7.1
  - samtools=1.9
  - pandas=0.24.2
  - multiqc=1.8

  ## peka dependencies
  - matplotlib=3.1.1
  - numpy=1.17.4
  - pybedtools=0.8.0
  - scipy=1.3.1
  - seaborn=0.9.0
  - plumbum=1.6.8
  - scikit-learn=0.21.3

  #- ucsc-bedgraphtobigwig=377

  #- pip
  #- pip: