name: dev-pipeline-testing

on:
#  pull_request:
#    branches: [ dev ]
  push:
    branches: [ workflow-testing ]

jobs:
  test-modules:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nxf_ver: ['20.01.0', '']
    steps:
      - uses: actions/checkout@v2

      - name: Install Nextflow
        run: |
          export NXF_VER=${{ matrix.nxf_ver }}
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: Download image
        run: |
          docker pull luslab/nextflow-clip:dev

      - name: Run module tests
        run: |
          nextflow run ${GITHUB_WORKSPACE}main.nf -profile docker,test