name: module-testing

on:
  pull_request:
    branches: [ dev ]
  push:
    branches: [ workflow-testing ]

jobs:
  test-modules:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nxf_ver: ['20.01.0', '']
        #aligner: ["--aligner 'hisat2'", "--aligner 'star'", "--pseudo_aligner 'salmon'"]
        #options: ['--skipQC', '--remove_rRNA', '--saveUnaligned', '--skipTrimming', '--star_index false']
    steps:
      - uses: actions/checkout@v2

      - name: Install Nextflow
        run: |
          export NXF_VER=${{ matrix.nxf_ver }}
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: Download image
        run: |
          docker pull luslab/nextflow-clip:dev

      - name: Test bowtie_rrna
        run: |
          nextflow run ${GITHUB_WORKSPACE}/modules/bowtie_rrna/test.nf -profile moduletest,github --classpath '/home/runner/work/group-nextflow-clip/group-nextflow-clip/groovy/NfUtils.groovy'
        
      - name: Test cutadapt
        run: |
          nextflow run ${GITHUB_WORKSPACE}/modules/cutadapt/test.nf -profile moduletest,github

      - name: Test fastqc
        run: |
          nextflow run ${GITHUB_WORKSPACE}/modules/fastqc/test.nf -profile moduletest,github
      
      - name: Test getcrosslink-coverage
        run: |
          nextflow run ${GITHUB_WORKSPACE}/modules/get-crosslink-coverage/test.nf -profile moduletest,github

      - name: Test get-crosslinks
        run: |
          nextflow run ${GITHUB_WORKSPACE}/modules/get-crosslinks/test.nf -profile moduletest,github

      - name: Test icount
        run: |
          nextflow run ${GITHUB_WORKSPACE}/modules/icount/test.nf -profile moduletest,github

      - name: Test paraclu
        run: |
          nextflow run ${GITHUB_WORKSPACE}/modules/paraclu/test.nf -profile moduletest,github

      - name: Test peka
        run: |
          nextflow run ${GITHUB_WORKSPACE}/modules/peka/test.nf -profile moduletest,github

      - name: Test samtools
        run: |
          nextflow run ${GITHUB_WORKSPACE}/modules/samtools/test.nf -profile moduletest,github

      - name: Test star
        run: |
           nextflow run ${GITHUB_WORKSPACE}/modules/star/test.nf -profile moduletest,github

      - name: Test umi-tools
        run: |
          nextflow run ${GITHUB_WORKSPACE}/modules/umi-tools/test.nf -profile moduletest,github

#      - name: Verify trim-read output
#        run: |
#          ./test/scripts/verify-checksum.sh "modules/cutadapt/output/*.gz" "results/cutadapt/*.gz"